/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * author gevindu
 * this interface for check bus arrival times,bus tickets-BUS
 */

import javax.swing.*; // For GUI components like JButton, JLabel, and JFileChooser
import java.awt.Image; // For image scaling
import java.awt.image.BufferedImage; // For reading images
import javax.imageio.ImageIO; // For reading image files
import java.io.*; // For file handling (FileInputStream, File, etc.)
import java.sql.*; // For database connectivity (Connection, PreparedStatement, etc.)

public class ADD_LOST_ITEMS extends javax.swing.JFrame {
    
    private JFileChooser fileChooser; // File chooser for browsing files
    private File selectedFile; // Selected file for the image
    
    public ADD_LOST_ITEMS() {
        initComponents();
        fileChooser = new JFileChooser(); // Initialize file chooser
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LOST_ITEM_COLOR = new javax.swing.JTextField();
        LOST_ITEM_TYPE1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        OWNER_NIC = new javax.swing.JTextField();
        OWNER_NAME = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PNO = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EMAIL = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ADDED_IMAGE = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        RESET_BUTTON1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel2.setText("ADD LOST ITEMS");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("OWNER NIC  :");

        LOST_ITEM_COLOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOST_ITEM_COLORActionPerformed(evt);
            }
        });

        LOST_ITEM_TYPE1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ELECTRONIC ITEM", "MONEY", "PURSE", "BOOK", "BOTTLE", "OTHER", " " }));
        LOST_ITEM_TYPE1.setSelectedItem(-1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("LOST ITEM TYPE   :");

        OWNER_NIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OWNER_NICActionPerformed(evt);
            }
        });

        OWNER_NAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OWNER_NAMEActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("LOST ITEM COLOUR : ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("OWNER NAME  :");

        PNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PNOActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("OWNER EMAIL   :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("OWNER CONTACT NO  :");

        EMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMAILActionPerformed(evt);
            }
        });

        description.setColumns(20);
        description.setRows(5);
        description.setBorder(null);
        jScrollPane1.setViewportView(description);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("DESCRIPTION    :");

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("BROWSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ADDED_IMAGE.setBackground(new java.awt.Color(204, 204, 255));
        ADDED_IMAGE.setText("you can see youe choosen picture here");
        ADDED_IMAGE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        RESET_BUTTON1.setBackground(new java.awt.Color(102, 102, 102));
        RESET_BUTTON1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        RESET_BUTTON1.setForeground(new java.awt.Color(255, 255, 255));
        RESET_BUTTON1.setText("BACK");
        RESET_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESET_BUTTON1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 64, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LOST_ITEM_TYPE1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OWNER_NAME)
                    .addComponent(OWNER_NIC)
                    .addComponent(LOST_ITEM_COLOR, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PNO, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EMAIL, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ADDED_IMAGE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RESET_BUTTON1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LOST_ITEM_TYPE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LOST_ITEM_COLOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OWNER_NIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OWNER_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ADDED_IMAGE, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(RESET_BUTTON1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LOST_ITEM_COLORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOST_ITEM_COLORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LOST_ITEM_COLORActionPerformed

    private void OWNER_NICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OWNER_NICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OWNER_NICActionPerformed

    private void OWNER_NAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OWNER_NAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OWNER_NAMEActionPerformed

    private void PNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PNOActionPerformed

    private void EMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EMAILActionPerformed

 private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
 int returnValue = fileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile();
            try {
                BufferedImage bi = ImageIO.read(selectedFile);
                if (bi != null) {
                    // Scale and display the image in the JLabel
                    Image img = bi.getScaledInstance(210, 210, Image.SCALE_SMOOTH);
                    ADDED_IMAGE.setText(""); // Clear placeholder text
                    ADDED_IMAGE.setIcon(new ImageIcon(img));
                } else {
                    JOptionPane.showMessageDialog(this, "Selected file is not a valid image.");
                    selectedFile = null; // Reset the selected file
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error loading image: " + ex.getMessage());
            }
        }
    }                                      
    private boolean validateFormInputs() {
        if (LOST_ITEM_TYPE1.getSelectedItem() == null ||
            LOST_ITEM_COLOR.getText().isEmpty() ||
            description.getText().isEmpty() ||
            OWNER_NIC.getText().isEmpty() ||
            OWNER_NAME.getText().isEmpty() ||
            PNO.getText().isEmpty() ||
            EMAIL.getText().isEmpty() ||
            selectedFile == null) {
            JOptionPane.showMessageDialog(this, "Please fill in all required fields and select an image.");
            return false;
        }
        return true;
    }                                        
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         

     if (validateFormInputs()) {
            try (FileInputStream fis = new FileInputStream(selectedFile)) {
                byte[] imageBytes = fis.readAllBytes(); // Read the image file as bytes

                // Database connection details
                String dbURL = "jdbc:mysql://localhost:3306/BUS";
                String dbUser = "root";
                String dbPassword = ""; // Replace with your database password

                // SQL query for inserting data
                String sql = "INSERT INTO LOST_ITEMS (LOST_ITEM_TYPE, LOST_ITEM_COLOR, LOST_ITEM_PHOTO, " +
                             "DESCRIPTION_ABOUT_ITEM, OWNER_NIC, OWNER_NAME, OWNER_CONTACT_NO, OWNER_EMAIL) " +
                             "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

                try (Connection conn = DriverManager.getConnection(dbURL, dbUser, dbPassword);
                     PreparedStatement pstmt = conn.prepareStatement(sql)) {

                    pstmt.setString(1, LOST_ITEM_TYPE1.getSelectedItem().toString()); // Dropdown for type
                    pstmt.setString(2, LOST_ITEM_COLOR.getText());
                    pstmt.setBytes(3, imageBytes);
                    pstmt.setString(4, description.getText()); // Text field for description
                    pstmt.setString(5, OWNER_NIC.getText());
                    pstmt.setString(6, OWNER_NAME.getText());
                    pstmt.setString(7, PNO.getText());
                    pstmt.setString(8, EMAIL.getText());

                    int rowsInserted = pstmt.executeUpdate();
                    if (rowsInserted > 0) {
                        JOptionPane.showMessageDialog(this, "Data successfully uploaded to the database!");
                    }
                }
            } catch (IOException | SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            }
        }
     //to reset entered data
     LOST_ITEM_COLOR.setText("");
     description.setText("");
     OWNER_NIC.setText("");
     OWNER_NAME.setText("");
     PNO.setText("");
     EMAIL.setText("");
     LOST_ITEM_COLOR.setText("");
     ADDED_IMAGE.setText("");
     selectedFile=null;
     ADDED_IMAGE.setIcon(null);
     
                                                                                      
    }                                      

    private void RESET_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESET_BUTTON1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_RESET_BUTTON1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADD_LOST_ITEMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADD_LOST_ITEMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADD_LOST_ITEMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADD_LOST_ITEMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADD_LOST_ITEMS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADDED_IMAGE;
    private javax.swing.JTextField EMAIL;
    private javax.swing.JTextField LOST_ITEM_COLOR;
    private javax.swing.JComboBox<String> LOST_ITEM_TYPE1;
    private javax.swing.JTextField OWNER_NAME;
    private javax.swing.JTextField OWNER_NIC;
    private javax.swing.JTextField PNO;
    private javax.swing.JButton RESET_BUTTON1;
    private javax.swing.JTextArea description;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
