/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gevindu
 * THIS IS FOR DISPALY LOST ITEMS - bus
 */
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.*;


 

 

 class ImageTableCellRenderer extends DefaultTableCellRenderer {
    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        if (value instanceof ImageIcon) {
            JLabel label = new JLabel((ImageIcon) value);
            // Adjust the size of the image if needed
            label.setPreferredSize(new Dimension(50, 50)); // Adjust size
            return label;
        }
        return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
    }
}
public class DisplayLostItems extends javax.swing.JFrame {
    
    private javax.swing.JTable lostItemsTable;
   // private javax.swing.JLabel DISPLAYLOSTITEMS;
    /**
     * Creates new form DisplayLostItems
     */
    
     public void delete7DayLostItems() {
    // Variables for database connection
    String jdbcUrl = "jdbc:mysql://localhost:3306/BUS"; // Database URL with database name (BUS)
    String username = "root"; // MySQL username (default is 'root')
    String password = ""; // MySQL password (leave empty if not set)

    try {
        // Load MySQL JDBC Driver
        Class.forName("com.mysql.cj.jdbc.Driver"); // Ensures the MySQL JDBC driver is available

        // Attempt to connect to the database
        try (Connection connection = DriverManager.getConnection(jdbcUrl, username, password)) {
            System.out.println("Connected to the database!");

            // SQL query to delete items reported more than 7 days ago
            String sqlQuery = "DELETE FROM LOST_ITEMS WHERE DATE_REPORTED <= NOW() - INTERVAL 7 DAY";

            // Use PreparedStatement to execute the query
            try (PreparedStatement preparedStatement = connection.prepareStatement(sqlQuery)) {
                // Execute the delete query
                int rowsAffected = preparedStatement.executeUpdate();

                // Provide feedback based on rows affected
                if (rowsAffected > 0) {
                    System.out.println(rowsAffected + " lost item(s) older than 7 days deleted.");
                } else {
                    System.out.println("No lost items older than 7 days to delete.");
                }
            }
        } catch (SQLException e) {
            // Handle SQL-related errors
            System.out.println("Database error.");
            e.printStackTrace(); // Print the stack trace for debugging
        }
    } catch (ClassNotFoundException e) {
        // Handle errors if the MySQL JDBC Driver is not found
        System.out.println("MySQL JDBC Driver not found.");
        e.printStackTrace(); // Print the stack trace for debugging
    }
}
    public DisplayLostItems() {
     //  initComponents1();
        delete7DayLostItems();
        initComponents1();
        fetchLostItems(); // Load data into the table when the frame initializes
        setDefaultCloseOperation(DisplayLostItems.DISPOSE_ON_CLOSE); // Set to DISPOSE
        setSize(800, 600); // Replace with desired dimensions
        setLocationRelativeTo(null); // Center after setting size
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
 
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("TABLE SHOWS IN THIS LABEL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 425, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void initComponents1() {
    // Initialize components
    
    jScrollPane1 = new javax.swing.JScrollPane();
    lostItemsTable = new javax.swing.JTable();

    // Set up the JFrame
    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    // Set up the label
 

    // Set up the table model and columns
    lostItemsTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {},
        new String [] {
             "Item Type", "Color", "Description", "NIC", "Owner Name", "Contact No", "Email", "Image"
        }
    ));

    // Apply the custom renderer to the last column (Image column, index 7)
    lostItemsTable.getColumnModel().getColumn(7).setCellRenderer(new ImageTableCellRenderer());

    // Add mouse listener to handle image click
    lostItemsTable.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int row = lostItemsTable.rowAtPoint(evt.getPoint());
            int column = lostItemsTable.columnAtPoint(evt.getPoint());
            // Check if the clicked column is the Image column (index 7)
            if (column == 7) {
                Object value = lostItemsTable.getValueAt(row, column);
                if (value instanceof ImageIcon imageIcon) {
                    displayBigImage(imageIcon); // Show the image in a larger view
                }
            }
        }
    });

    // Add the table to the scroll pane
    jScrollPane1.setViewportView(lostItemsTable);

    // Layout settings for JFrame
    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
    );

    // Final pack to apply the layout and size
    pack();
}
private void displayBigImage(ImageIcon imageIcon) {
    // Create a JDialog to display the image in its original size
    JDialog imageDialog = new JDialog(this, "Large Image", true);
    imageDialog.setLayout(new BorderLayout());

    // Create a label to display the image
    JLabel label = new JLabel(imageIcon);
    label.setHorizontalAlignment(JLabel.CENTER);

    // Wrap the label in a JScrollPane to make it scrollable (in case the image is too large)
    JScrollPane scrollPane = new JScrollPane(label);
    imageDialog.add(scrollPane, BorderLayout.CENTER);

    // Get the original size of the image
    int imageWidth = imageIcon.getIconWidth();
    int imageHeight = imageIcon.getIconHeight();

    // Set the dialog size to the image's original size
    imageDialog.setSize(imageWidth, imageHeight);

    // Center the dialog and make it visible
    imageDialog.setLocationRelativeTo(null); // Center the dialog on the screen
    imageDialog.setVisible(true);
}
private void fetchLostItems() {
    String dbURL = "jdbc:mysql://localhost:3306/BUS";
    String dbUser = "root";
    String dbPassword = ""; // Replace with your database password if needed

    String sql = "SELECT * FROM LOST_ITEMS";

    try (Connection conn = DriverManager.getConnection(dbURL, dbUser, dbPassword);
         Statement stmt = conn.createStatement();
         ResultSet rs = stmt.executeQuery(sql)) {

        DefaultTableModel model = (DefaultTableModel) lostItemsTable.getModel();

        while (rs.next()) {
            // Retrieve image as byte array (BLOB)
            byte[] imageBytes = rs.getBytes("LOST_ITEM_PHOTO"); // Adjust column name to match your DB

            // Convert byte array to ImageIcon
            ImageIcon imageIcon = new ImageIcon(imageBytes);
            // Add row data including ImageIcon
            model.addRow(new Object[]{
                rs.getString("LOST_ITEM_TYPE"),
                rs.getString("LOST_ITEM_COLOR"),
                rs.getString("DESCRIPTION_ABOUT_ITEM"),
                rs.getString("OWNER_NIC"),
                rs.getString("OWNER_NAME"),
                rs.getString("OWNER_CONTACT_NO"),
                rs.getString("OWNER_EMAIL"),
                imageIcon // Store the ImageIcon in the table model
            });
        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error fetching data: " + ex.getMessage());
    }
}
    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> {
            new DisplayLostItems().setVisible(true);
    });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
