


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gevindu
 * this is for display reservation process-BUS
 */
import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
public class DisplayReservations extends javax.swing.JFrame {
   public static void showreservations(JPanel PANEL_1) {
 // Remove all existing components from PANEL_1
  PANEL_1.removeAll();

    // Create DefaultTableModel with column headers matching your table
    DefaultTableModel tableModel = new DefaultTableModel(new String[]{
       "RESERVER_NAME","BOOKER_NIC","START_DATE","END_DATE","NOOFBUSES","ACSTATUS","PICKUPLOCATION","PNO1","NOOFDAYS"
    }, 0);

    // Create JTable and add it to a JScrollPane
    JTable table = new JTable(tableModel);
    JScrollPane scrollPane = new JScrollPane(table);

    // Add JScrollPane to PANEL_1
    PANEL_1.add(scrollPane);

    // Database connection and data retrieval
    try {
        // Connect to the database
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/BUS", "root", "");
        
        // Query to fetch data 
        String query = "SELECT * FROM BUS_RESERVATIONS";
        PreparedStatement pstmt = conn.prepareStatement(query);


ResultSet rs = pstmt.executeQuery();

        // Populate the table with data from ResultSet
        while (rs.next()) {
            String RESERVER_NAME = rs.getString("RESERVER_NAME");
            String BOOKER_NIC = rs.getString("BOOKER_NIC");
            String START_DATE = rs.getString("START_DATE");
            String END_DATE = rs.getString("END_DATE");
            String NOOFBUSES = rs.getString("NOOFBUSES");
            String ACSTATUS = rs.getString("ACSTATUS");
            String PICKUPLOCATION = rs.getString("PICKUPLOCATION");
            String PNO1 = rs.getString("PNO1");
            String NOOFDAYS = rs.getString("NOOFDAYS");
            
            
           
            // Add a row to the table model
            tableModel.addRow(new Object[]{RESERVER_NAME, BOOKER_NIC, START_DATE, END_DATE, NOOFBUSES, ACSTATUS, PICKUPLOCATION, PNO1, NOOFDAYS});
        }

        // Close connections
        rs.close();
        pstmt.close();
        conn.close();

    } catch (SQLException e) {
        // Show error message in case of a database error
        JOptionPane.showMessageDialog(PANEL_1, "Error loading data: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }

    // Refresh the panel to show the newly added components
    PANEL_1.revalidate(); // Revalidate to refresh the panel
    PANEL_1.repaint();   // Repaint to ensure the changes are displayed
    
       }
    /**
     * Creates new form DisplayReservations
     */
    public DisplayReservations() {
        initComponents();
        showreservations( PANEL_1) ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PANEL_1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PANEL_1.setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PANEL_1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PANEL_1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayReservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayReservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayReservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayReservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayReservations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PANEL_1;
    // End of variables declaration//GEN-END:variables
}
