/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * @author gevindu
 * LOGIN form - BUS
 * This class represents the login form of the BUS system. 
 * It allows users to enter their NIC and password to authenticate and access the system.
 */

import java.awt.Desktop;
import java.net.URI;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

public class LOGIN extends javax.swing.JFrame {
   
    public LOGIN() {
        initComponents();// Initializes the GUI components (auto-generated by the form designer)
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        TXTNIC_AS_USERNAME = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TXTPASSWORD = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(java.awt.Color.black);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setForeground(new java.awt.Color(0, 51, 51));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(java.awt.SystemColor.controlHighlight);
        jPanel1.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.setAutoscrolls(true);
        jPanel1.setFocusTraversalPolicyProvider(true);
        jPanel1.setName("4"); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOG IN");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel1.setText("Beacon Utility System");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("ENTER NIC as USERNAME :");

        jLabel4.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        jLabel4.setText("BUS");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("ENTER PASSWORD            :");

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jButton2.setText("SIGN UP");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("forgot your password ?");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 0, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("delete my account");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("click to downlord User Guide Manual");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(202, 202, 202))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(TXTNIC_AS_USERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(TXTPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 34, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TXTNIC_AS_USERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TXTPASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
// Variables for database connection
String jdbcUrl = "jdbc:mysql://localhost:3306/BUS"; // Database URL with database name (BUS)
String username = "root"; // MySQL username (default is 'root')
String password = ""; // MySQL password (leave empty if not set)

// Use try-catch to handle exceptions for JDBC driver loading and database connection
try {
    // Load MySQL JDBC Driver
    Class.forName("com.mysql.cj.jdbc.Driver"); // Ensures the MySQL JDBC driver is available

    // Attempt to connect to the database
    try (Connection connection = DriverManager.getConnection(jdbcUrl, username, password)) {
        System.out.println("Connected to the database!"); // Confirmation message for successful connection

        // Retrieve NIC and password entered by the user from the GUI text fields
        String enteredNIC = TXTNIC_AS_USERNAME.getText(); // NIC entered as the username
        String enteredPASSWORD = new String(TXTPASSWORD.getPassword()); // Password entered by the user

        // SQL query to check if the entered NIC and password exist in either the PASSWORD table or STAFF table
        String sqlQuery = "SELECT NIC, PASSWORD FROM PASSWORD WHERE NIC = ? AND PASSWORD = ? " +
                          "UNION " +
                          "SELECT ONIC, OPASSWORD FROM STAFF WHERE ONIC = ? AND OPASSWORD = ?";

        // Use PreparedStatement to securely set the values in the query to prevent SQL injection
        try (PreparedStatement preparedStatement = connection.prepareStatement(sqlQuery)) {
            // Set parameters for the first table (PASSWORD)
            preparedStatement.setString(1, enteredNIC); // Set the first placeholder (?) to the entered NIC
            preparedStatement.setString(2, enteredPASSWORD); // Set the second placeholder (?) to the entered password
            
            // Set parameters for the second table (STAFF)
            preparedStatement.setString(3, enteredNIC); // Set the third placeholder (?) to the entered NIC
            preparedStatement.setString(4, enteredPASSWORD); // Set the fourth placeholder (?) to the entered password

            // Execute the query and store the result in a ResultSet
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) { 
                    // If a record is found, the login is successful
                    System.out.println("NIC and PASSWORD found in the database. Login successful.");
                    javax.swing.JOptionPane.showMessageDialog(this, "NIC and PASSWORD found in the database. Login successful.");
                    // Open the dashboard form after successful login
                    // Close the current login form (optional if you want only one window at a time)
                    this.dispose(); // Dispose of the current login window
                    new DASHBOARD().setVisible(true); // Display the dashboard
                } else {
                    // If no matching record is found, the NIC or password is invalid
                    System.out.println("Invalid NIC or password.");
                    javax.swing.JOptionPane.showMessageDialog(this, "Invalid NIC or password."); // Show error message
                }
            }
        }
    } catch (SQLException e) {
        // Handle SQL-related errors, such as connection issues or query execution problems
        System.out.println("Database error.");
        e.printStackTrace(); // Print the stack trace for debugging
    }
} catch (ClassNotFoundException e) {
    // Handle errors if the MySQL JDBC Driver is not found
    System.out.println("MySQL JDBC Driver not found.");
    e.printStackTrace(); // Print the stack trace for debugging
}
    }//GEN-LAST:event_jButton1MousePressed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
       // Action performed when the "Register" button is clicked (assuming button action is registered)
       new REG_NORMAL__USER().setVisible(true); // Open the registration form (REG_NORMAL_USER)
       this.dispose(); // Close the current login form
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                  // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       // Open the password reset form (RESET_PASSWORD) when the label is clicked
       new RESET_PASSWORD().setVisible(true); // Display the RESET_PASSWORD form
       this.dispose(); // Close the current form (login) after opening the reset password form
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if (TXTNIC_AS_USERNAME.getText().isEmpty() || new String(TXTPASSWORD.getPassword()).isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Enter NIC & Password to delete your account");
} else {
     int response =  JOptionPane.showConfirmDialog(this,"Are you sure you want to delete your accout?","Confirm Exit",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
                    String jdbcUrl = "jdbc:mysql://localhost:3306/BUS";
    String username = "root";
    String password = "";

    try {
        // Load MySQL JDBC Driver
        Class.forName("com.mysql.cj.jdbc.Driver");

        // Connect to the database
        try (Connection connection = DriverManager.getConnection(jdbcUrl, username, password)) {
            System.out.println("Connected to the database!");

            // Retrieve NIC and password entered by the user
            String nic = TXTNIC_AS_USERNAME.getText();
            String userPassword = new String(TXTPASSWORD.getPassword());

            // SQL queries to delete records from both tables
            String deleteFromNormalUser = "DELETE FROM NORMAL_USER WHERE NIC = ?";
            String deleteFromPassword = "DELETE FROM PASSWORD WHERE NIC = ? AND PASSWORD = ?";

            // Delete from NORMAL_USER table
            try (PreparedStatement deleteNormalUserStmt = connection.prepareStatement(deleteFromNormalUser)) {
                deleteNormalUserStmt.setString(1, nic);
                int rowsDeletedNormalUser = deleteNormalUserStmt.executeUpdate();

                // Delete from PASSWORD table
                try (PreparedStatement deletePasswordStmt = connection.prepareStatement(deleteFromPassword)) {
                    deletePasswordStmt.setString(1, nic);
                    deletePasswordStmt.setString(2, userPassword);
                    int rowsDeletedPassword = deletePasswordStmt.executeUpdate();

                    if (rowsDeletedNormalUser > 0 || rowsDeletedPassword > 0) {
                        // Records deleted successfully
                        System.out.println("Your BUS account was deleted. Thank you!");
                        javax.swing.JOptionPane.showMessageDialog(this, "Your BUS account was deleted. Thank you!");
                        System.exit(0);
                    } else {
                        // No matching record found
                        System.out.println("Invalid NIC or Password.");
                        javax.swing.JOptionPane.showMessageDialog(this, "Invalid NIC or Password.");
                        
                    }
                }
            }
        } catch (SQLException e) {
            // Handle SQL-related errors
            System.out.println("Database error.");
            e.printStackTrace();
        }
    } catch (ClassNotFoundException e) {
        // Handle errors if the MySQL JDBC Driver is not found
        System.out.println("MySQL JDBC Driver not found.");
        e.printStackTrace();
    }
                }
    // Database connection details
   
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try{
    Desktop desktop = Desktop.getDesktop();
    desktop.browse(new URI("https://drive.google.com/file/d/1ox5j7E3hGmrQnGXFWs3HKldCgjHI-q9v/view?usp=sharing"));
  
} catch(Exception e){
    e.printStackTrace();
    javax.swing.JOptionPane.showMessageDialog(this, "unable to open the web page:"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
    }     
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        // Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTNIC_AS_USERNAME;
    private javax.swing.JPasswordField TXTPASSWORD;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}