/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/*
*this is for normal user registation process- BUS
*/
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;

public class REG_NORMAL__USER extends javax.swing.JFrame {
   
    //set combo box 2 items automatically
    private void updateCombox2Items() {
        combox2.removeAllItems();  // Clear previous items

        // Check selected item in combox1 and update combox2
        if (combox1.getSelectedItem().equals("Kalutara")) {
            Needmethod.A.Kalutara();
        } else if (combox1.getSelectedItem().equals("Colombo")) {
            Needmethod.A.Colombo();    
        }
    }

    public void Districtchoose() {
    
        // Add ActionListener to combox1
        combox1.addActionListener(new ActionListener() {
            @Override
             public void actionPerformed(ActionEvent e) {
                updateCombox2Items();
            }
        });
        
        // Initial update of combox2 based on default selection
        updateCombox2Items();
    }

    private void Living_areachoose() {
    combox3.removeAllItems();  // Clear previous items

    // Check if combox2 has a selected item to avoid NullPointerException
    Object selectedItem = combox2.getSelectedItem();
    if (selectedItem == null) {
        return;  // Exit the method if there's no selection
    }

    // Check selected item in combox2 and update combox3 based on its value
    if (selectedItem.equals("Panadura")) {
         Needmethod.A.Panadura();
    } else if (selectedItem.equals("Horana")) {
         Needmethod.A.Horana();
    }
    else if (selectedItem.equals("Bandaragama")) {
         Needmethod.A.Bandaragama();
    }
    else if (selectedItem.equals("Mathugama")) {
         Needmethod.A.Mathugama();
    }
    else if (selectedItem.equals("Beruwala")) {
        Needmethod.A.Beruwala();
    }
 
    else if (selectedItem.equals("Dehiwala")) {
        Needmethod.A.Dehiwala();
     }
    else if (selectedItem.equals("Wellawatte")) {
        Needmethod.A.Wellawatte();
}
    else if (selectedItem.equals("Bambalapitiya")) {
        Needmethod.A.Bambalapitiya();
    }
    else if (selectedItem.equals("Kollupitiya")) {
    
         Needmethod.A.Kollupitiya();
            }
    else if (selectedItem.equals("Galle face")) {
         Needmethod.A.Galle_face();
   
}
    
}
    public REG_NORMAL__USER() {
            initComponents();
            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setFocusableWindowState(true); // Enable focusability for the window
            setFocusable(true); // Ensure frame is focusable
            setResizable(false); // Keep the window size fixed
            setLocationRelativeTo(null); // Center the window on the screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NU_NIC = new javax.swing.JTextField();
        NU_FNAME = new javax.swing.JTextField();
        NU_LNAME = new javax.swing.JTextField();
        NU_PNO = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        combox3 = new javax.swing.JComboBox<>();
        combox2 = new javax.swing.JComboBox<>();
        REjiSTER = new javax.swing.JButton();
        RESET_BUTTON1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        combox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        NU_RE_ENTERED_PASSWORD = new javax.swing.JPasswordField();
        NU_PASSWORD = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setFocusableWindowState(false);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setFocusCycleRoot(true);
        jPanel1.setFocusTraversalPolicyProvider(true);
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NU_NIC.setFocusCycleRoot(true);
        NU_NIC.setFocusTraversalPolicyProvider(true);
        NU_NIC.setInheritsPopupMenu(true);
        NU_NIC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NU_NICMousePressed(evt);
            }
        });
        jPanel1.add(NU_NIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 74, 212, -1));
        jPanel1.add(NU_FNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 108, 212, -1));
        jPanel1.add(NU_LNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 142, 210, -1));
        jPanel1.add(NU_PNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 176, 210, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("ENTER FNAME                         :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 108, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("CHOOSE CURRENT LIVING AREA  :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 346, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("ENTER NIC                               :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 74, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("ENTER LNAME                         :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 142, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("CHOOSE DISTRICT                          :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 306, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("CHOOSE NEAREST BUS-HALT       :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 386, -1, -1));

        combox3.setSelectedIndex(-1);
        jPanel1.add(combox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 386, 162, -1));

        combox2.setSelectedIndex(-1);
        combox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combox2ActionPerformed(evt);
            }
        });
        jPanel1.add(combox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 346, 161, -1));

        REjiSTER.setBackground(new java.awt.Color(0, 153, 255));
        REjiSTER.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        REjiSTER.setForeground(new java.awt.Color(255, 255, 255));
        REjiSTER.setText("REJISTER");
        REjiSTER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                REjiSTERMousePressed(evt);
            }
        });
        REjiSTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REjiSTERActionPerformed(evt);
            }
        });
        jPanel1.add(REjiSTER, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 457, 147, -1));

        RESET_BUTTON1.setBackground(new java.awt.Color(102, 102, 102));
        RESET_BUTTON1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        RESET_BUTTON1.setForeground(new java.awt.Color(255, 255, 255));
        RESET_BUTTON1.setText("BACK");
        RESET_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESET_BUTTON1ActionPerformed(evt);
            }
        });
        jPanel1.add(RESET_BUTTON1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 457, 142, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("ENTER PNO                              :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 176, -1, -1));

        combox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kalutara", "Colombo" }));
        combox1.setSelectedIndex(-1);
        combox1.setSelectedItem(-1);
        combox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combox1ActionPerformed(evt);
            }
        });
        jPanel1.add(combox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 306, 161, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("ENTER NEW PASSWORD        :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 216, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("RE ENTER NEW PASSWORD  :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 250, -1, -1));
        jPanel1.add(NU_RE_ENTERED_PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 208, -1));

        NU_PASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NU_PASSWORDActionPerformed(evt);
            }
        });
        jPanel1.add(NU_PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 216, 208, -1));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel1.setText("NORMAL USER REJISTATION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 0, -1, 50));

        getContentPane().add(jPanel1);
        jPanel1.getAccessibleContext().setAccessibleParent(jPanel1);

        getAccessibleContext().setAccessibleParent(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void combox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combox1ActionPerformed
        Districtchoose();
    }//GEN-LAST:event_combox1ActionPerformed

    private void RESET_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESET_BUTTON1ActionPerformed
        new LOGIN().setVisible(true);//to open again login form
       this.dispose(); //to close reset password form
    }//GEN-LAST:event_RESET_BUTTON1ActionPerformed

    private void REjiSTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REjiSTERActionPerformed
// Variables for database connection
String jdbcUrl = "jdbc:mysql://localhost:3306/BUS"; // Database URL with database name (BUS)
String username = "root"; // MySQL username (default is 'root')
String password = ""; // MySQL password (leave empty if not set)

try {
    // Load MySQL JDBC Driver
    Class.forName("com.mysql.cj.jdbc.Driver");

    // Connect to the database
    try (Connection connection = DriverManager.getConnection(jdbcUrl, username, password)) {
        System.out.println("Connected to the database!");

        // Collect data from form fields
        String enteredNUNIC                  = NU_NIC.getText();
        String enteredNUFName                = NU_FNAME.getText();
        String enteredNULName                = NU_LNAME.getText();
        String enteredNUPNO                  = NU_PNO.getText();
        String enteredNUPassword             = new String(NU_PASSWORD.getPassword());
        String enteredNU_Re_entered_password = new String(NU_RE_ENTERED_PASSWORD.getPassword());
        String enteredNU_District            = (String) combox1.getSelectedItem();
        String enteredNU_living_area         = (String) combox2.getSelectedItem();
        String enteredNUNearest_bus_halt     = (String) combox3.getSelectedItem();

        // Check if passwords match
        if (!enteredNUPassword.equals(enteredNU_Re_entered_password)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Passwords do not match.");
            return; // Exit early if passwords don't match
        }

        // Check for empty or null fields
        if (enteredNUNIC.isEmpty() || enteredNUFName.isEmpty() || enteredNULName.isEmpty() ||
            enteredNUPNO.isEmpty() || enteredNUPassword.isEmpty() || enteredNU_District == null ||
            enteredNU_living_area == null || enteredNUNearest_bus_halt == null) 
             {
              javax.swing.JOptionPane.showMessageDialog(this, "Please fill out all fields.");
              return; // Exit if any field is empty or null
             }

        // SQL queries for inserting data into two tables
        //insert to user details table
        String sqlQuery1 = "INSERT INTO normal_user (NIC, FName, LName, PNO, Password, District, LIVING_AREA, NEAREST_BUS_HALT) " +
                           "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        //insert to password checking table
        String sqlQuery2 = "INSERT INTO Password (NIC, PASSWORD) VALUES (?, ?)";

        // First query: Insert data into 'normal_user' table
        try (PreparedStatement preparedStatement1 = connection.prepareStatement(sqlQuery1)) {
            // Set parameters for the first query
            preparedStatement1.setString(1, enteredNUNIC);              // NIC
            preparedStatement1.setString(2, enteredNUFName);            // FName
            preparedStatement1.setString(3, enteredNULName);            // LName
            preparedStatement1.setString(4, enteredNUPNO);              // PNO
            preparedStatement1.setString(5, enteredNUPassword);         // Password
            preparedStatement1.setString(6, enteredNU_District);        // District
            preparedStatement1.setString(7, enteredNU_living_area);     // LIVING_AREA
            preparedStatement1.setString(8, enteredNUNearest_bus_halt); // NEAREST_BUS_HALT

            int rowsAffected1 = preparedStatement1.executeUpdate(); // Execute first query
            if (rowsAffected1 == 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error occurred while saving user data.");
                return;
            }

            // Second query: Insert data into 'Password' table
            try (PreparedStatement preparedStatement2 = connection.prepareStatement(sqlQuery2)) {
                // Set parameters for the second query
                preparedStatement2.setString(1, enteredNUNIC);              // NIC
                preparedStatement2.setString(2, enteredNU_Re_entered_password); // Password

                int rowsAffected2 = preparedStatement2.executeUpdate(); // Execute second query
                if (rowsAffected2 == 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Error occurred while saving password.");
                    return;
                }
            }

            // If both insertions were successful, show success message
            System.out.println("Data Saved");
            javax.swing.JOptionPane.showMessageDialog(this, "Data saved successfully!");
            this.dispose(); // Close the window
            new LOGIN().setVisible(true);
        } catch (SQLException e) {
            System.out.println("Error during database operations.");
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error during data saving. Please try again later.");
        }
    } catch (SQLException e) {
        System.out.println("Database connection error.");
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Database connection error. Please try again later.");
    }
} catch (ClassNotFoundException e) {
    System.out.println("MySQL JDBC Driver not found.");
    e.printStackTrace();
    javax.swing.JOptionPane.showMessageDialog(this, "JDBC Driver not found. Please check your configuration.");
}


    }//GEN-LAST:event_REjiSTERActionPerformed

    private void REjiSTERMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REjiSTERMousePressed
// Variables for database connection
String jdbcUrl = "jdbc:mysql://localhost:3306/BUS"; // Database URL with database name (BUS)
String username = "root"; // MySQL username (default is 'root')
String password = ""; // MySQL password (leave empty if not set)


        try {
            // Load MySQL JDBC Driver
            Class.forName("com.mysql.cj.jdbc.Driver");

            // Connect to the database
            try (Connection connection = DriverManager.getConnection(jdbcUrl, username, password)) {
                System.out.println("Connected to the database!");

                // Prepare SQL query to check if NIC and password are correct
                String enteredNIC = NU_NIC.getText();
                //String enteredPASSWORD = new String(TXTPASSWORD.getPassword());

                String sqlQuery = "SELECT * FROM PASSWORD WHERE NIC = ? AND PASSWORD = ?";
                try (PreparedStatement preparedStatement = connection.prepareStatement(sqlQuery)) {
                    // Set parameters
                    preparedStatement.setString(1, enteredNIC);
                    //preparedStatement.setString(2, enteredPASSWORD);

                    // Execute the query
                    try (ResultSet resultSet = preparedStatement.executeQuery()) {
                        if (resultSet.next()) {
                            // NIC and password found, login successfully
                            System.out.println("NIC and PASSWORD found in the database. Login successful.");
                            // new REG().setVisible(true);
                            this.dispose(); // Close the login form
                        } else {
                            // NIC or password not found
                            System.out.println("Invalid NIC or password.");
                            javax.swing.JOptionPane.showMessageDialog(this, "Invalid NIC or password.");
                        }
                    }
                }
            } catch (SQLException e) {
                System.out.println("Database error.");
                e.printStackTrace();
            }
        } catch (ClassNotFoundException e) {
            System.out.println("MySQL JDBC Driver not found.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_REjiSTERMousePressed

    private void combox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combox2ActionPerformed
          Living_areachoose();
    }//GEN-LAST:event_combox2ActionPerformed

    private void NU_PASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NU_PASSWORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NU_PASSWORDActionPerformed

    private void NU_NICMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NU_NICMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NU_NICMousePressed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REG_NORMAL__USER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REG_NORMAL__USER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REG_NORMAL__USER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REG_NORMAL__USER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new REG_NORMAL__USER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NU_FNAME;
    private javax.swing.JTextField NU_LNAME;
    private javax.swing.JTextField NU_NIC;
    private javax.swing.JPasswordField NU_PASSWORD;
    private javax.swing.JTextField NU_PNO;
    private javax.swing.JPasswordField NU_RE_ENTERED_PASSWORD;
    private javax.swing.JButton RESET_BUTTON1;
    private javax.swing.JButton REjiSTER;
    protected static javax.swing.JComboBox<String> combox1;
    protected static javax.swing.JComboBox<String> combox2;
    protected static javax.swing.JComboBox<String> combox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
