/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.SQLException;

/**
 *
 * @author gevindu
 * this is for update password-BUS
 */
public class RESET_PASSWORD extends javax.swing.JFrame {

    /**
     * Creates new form RESET_PASSWORD
     */
    public RESET_PASSWORD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RESET_BUTTON = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        REJISTERED_NIC = new javax.swing.JTextField();
        RETYPED_NEW_PASSWORD = new javax.swing.JPasswordField();
        NEW_PASSWORD = new javax.swing.JPasswordField();
        RESET_BUTTON1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setFocusTraversalPolicyProvider(true);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jPanel1.setBackground(java.awt.SystemColor.controlHighlight);
        jPanel1.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.setAutoscrolls(true);
        jPanel1.setFocusCycleRoot(true);
        jPanel1.setFocusTraversalPolicyProvider(true);
        jPanel1.setName("4"); // NOI18N

        RESET_BUTTON.setBackground(new java.awt.Color(255, 102, 102));
        RESET_BUTTON.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        RESET_BUTTON.setText("RESET");
        RESET_BUTTON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RESET_BUTTONMousePressed(evt);
            }
        });
        RESET_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESET_BUTTONActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel1.setText("RESET PASSWORD");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("ENTER NIC                            :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("ENTER NEW PASSWORD     :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("RETYPE NEW PASSWORD   :");

        RESET_BUTTON1.setBackground(new java.awt.Color(102, 102, 102));
        RESET_BUTTON1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        RESET_BUTTON1.setForeground(new java.awt.Color(255, 255, 255));
        RESET_BUTTON1.setText("BACK");
        RESET_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESET_BUTTON1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(2, 2, 2))
                    .addComponent(jLabel5)
                    .addComponent(RESET_BUTTON1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RESET_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(REJISTERED_NIC, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RETYPED_NEW_PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NEW_PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(154, 154, 154))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(REJISTERED_NIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(NEW_PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(RETYPED_NEW_PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RESET_BUTTON)
                    .addComponent(RESET_BUTTON1))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RESET_BUTTONMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RESET_BUTTONMousePressed

    }//GEN-LAST:event_RESET_BUTTONMousePressed

    private void RESET_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESET_BUTTONActionPerformed
String jdbcUrl = "jdbc:mysql://localhost:3306/BUS"; // Replace with your database name
String username = "root"; // Replace with your MySQL username
String password = ""; // Replace with your MySQL password

DatabaseManager dbManager = new DatabaseManager(jdbcUrl, username, password);

try {
    dbManager.connect(); // Connect to the database

    // Get user inputs
    String registeredNIC = REJISTERED_NIC.getText();
    String newPASSWORD = new String(NEW_PASSWORD.getPassword());
    String retypedPASSWORD = new String(RETYPED_NEW_PASSWORD.getPassword());

    // Null or empty input check
    if (registeredNIC.isEmpty() || newPASSWORD.isEmpty() || retypedPASSWORD.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "All fields must be filled out.");
        return;
    }

    // Check if NIC exists in either table
    if (!dbManager.doesNICExist(registeredNIC)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid NIC, try again...");
    } else if (newPASSWORD.equals(retypedPASSWORD)) {
        System.out.println("Passwords match: '" + newPASSWORD + "' and '" + retypedPASSWORD + "'");

        // Update password in both tables
        boolean passwordUpdated = dbManager.updatePasswordTable(registeredNIC, retypedPASSWORD);
        boolean staffUpdated = dbManager.updateStaffTable(registeredNIC, retypedPASSWORD);

        if (passwordUpdated || staffUpdated) {
            System.out.println("Password updated successfully.");
            javax.swing.JOptionPane.showMessageDialog(this, "Password updated successfully.");
            this.dispose();
            new LOGIN().setVisible(true);
        } else {
            System.out.println("Failed to update password.");
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to update password.");
        }
    } else {
        System.out.println("Passwords do not match: '" + newPASSWORD + "' and '" + retypedPASSWORD + "'");
        javax.swing.JOptionPane.showMessageDialog(this, "Passwords do not match.");
    }

} catch (ClassNotFoundException e) {
    System.out.println("MySQL JDBC Driver not found.");
    e.printStackTrace();
} catch (SQLException e) {
    System.out.println("Database error.");
    e.printStackTrace();
} finally {
    dbManager.disconnect(); // Ensure the connection is closed
}   
    }//GEN-LAST:event_RESET_BUTTONActionPerformed

    private void RESET_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESET_BUTTON1ActionPerformed
        new LOGIN().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RESET_BUTTON1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RESET_PASSWORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RESET_PASSWORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RESET_PASSWORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RESET_PASSWORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RESET_PASSWORD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField NEW_PASSWORD;
    private javax.swing.JTextField REJISTERED_NIC;
    private javax.swing.JButton RESET_BUTTON;
    private javax.swing.JButton RESET_BUTTON1;
    private javax.swing.JPasswordField RETYPED_NEW_PASSWORD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
