/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gevindu
 * this code is for update ticket price-BUS
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
public class UPDATE_TICKET_PRICE extends javax.swing.JFrame {

    /**
     * Creates new form UPDATE_TICKET_PRICE
     */
    public UPDATE_TICKET_PRICE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MAX3HALTPRICE = new javax.swing.JTextField();
        OVER3HALTPRICE = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        UPDATE_PRICE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel1.setText("UPDATE TICKET PRICE");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("ENTER NEW OVER 3 HALTS PRICE :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("ENTER NEW MAX 3 HALTS PRICE  :");

        UPDATE_PRICE.setBackground(new java.awt.Color(0, 204, 0));
        UPDATE_PRICE.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        UPDATE_PRICE.setForeground(new java.awt.Color(255, 255, 255));
        UPDATE_PRICE.setText("UPDATE PRICE");
        UPDATE_PRICE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UPDATE_PRICEMousePressed(evt);
            }
        });
        UPDATE_PRICE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATE_PRICEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(OVER3HALTPRICE, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MAX3HALTPRICE, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(UPDATE_PRICE, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MAX3HALTPRICE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OVER3HALTPRICE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addComponent(UPDATE_PRICE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UPDATE_PRICEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPDATE_PRICEMousePressed
      
       
    }//GEN-LAST:event_UPDATE_PRICEMousePressed

    private void UPDATE_PRICEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATE_PRICEActionPerformed
 
String jdbcUrl = "jdbc:mysql://localhost:3306/BUS"; // Replace with your database name
String username = "root"; // Replace with your MySQL username
String password = ""; // Replace with your MySQL password

try (Connection connection = DriverManager.getConnection(jdbcUrl, username, password)) {
    System.out.println("Connected to the database!");

    // Retrieve prices from the form
    String max3haltprice = MAX3HALTPRICE.getText();
    String over3haltprice = OVER3HALTPRICE.getText();

    // Use the COALESCE function to update only the fields that are provided
    String sqlQuery = "UPDATE TICKET_PRICE " +
                      "SET MAX3Halts = COALESCE(?, MAX3Halts), " +
                      "OVER3Halts = COALESCE(?, OVER3Halts)";

    try (PreparedStatement preparedStatement = connection.prepareStatement(sqlQuery)) {
        // If a price is not provided, pass NULL so the current value is retained
        preparedStatement.setString(1, max3haltprice.isEmpty() ? null : max3haltprice);
        preparedStatement.setString(2, over3haltprice.isEmpty() ? null : over3haltprice);

        int rowsUpdated = preparedStatement.executeUpdate();

        if (rowsUpdated > 0) {
            System.out.println("Ticket price updated successfully.");
            javax.swing.JOptionPane.showMessageDialog(this, "Ticket price updated successfully.");
            this.dispose();
           
            
        } else {
            System.out.println("Failed to update ticket price.");
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to update ticket price.");
        }
    }
} catch (SQLException e) {
    System.out.println("Database error.");
    e.printStackTrace();

 }
    }//GEN-LAST:event_UPDATE_PRICEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UPDATE_TICKET_PRICE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UPDATE_TICKET_PRICE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UPDATE_TICKET_PRICE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UPDATE_TICKET_PRICE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UPDATE_TICKET_PRICE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MAX3HALTPRICE;
    private javax.swing.JTextField OVER3HALTPRICE;
    private javax.swing.JButton UPDATE_PRICE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
