/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/*
 *this is for update normal user details-BUS
 */

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

public class UPDATE_NORMAL__USER_1 extends javax.swing.JFrame {
    
    //set combo box 2 items automatically
    private void updateCombox2Items() {
        combox2.removeAllItems();  // Clear previous items

        // Check selected item in combox1 and update combox2
        if (combox1.getSelectedItem().equals("Kalutara")) {
            Needmethod2.Kalutara();
        } else if (combox1.getSelectedItem().equals("Colombo")) {
            Needmethod2.Colombo();    
        }
    }

    public void Districtchoose() {
    
        // Add ActionListener to combox1
        combox1.addActionListener(new ActionListener() {
            @Override
             public void actionPerformed(ActionEvent e) {
                updateCombox2Items();
            }
        });
        
        // Initial update of combox2 based on default selection
        updateCombox2Items();
    }

    private void Living_areachoose() {
    combox3.removeAllItems();  // Clear previous items

    // Check if combox2 has a selected item to avoid NullPointerException
    Object selectedItem = combox2.getSelectedItem();
    if (selectedItem == null) {
        return;  // Exit the method if there's no selection
    }

    // Check selected item in combox2 and update combox3 based on its value
    if (selectedItem.equals("Panadura")) {
         Needmethod2.Panadura();
    } else if (selectedItem.equals("Horana")) {
         Needmethod2.Horana();
    }
    else if (selectedItem.equals("Bandaragama")) {
         Needmethod2.Bandaragama();
    }
    else if (selectedItem.equals("Mathugama")) {
         Needmethod2.Mathugama();
    }
    else if (selectedItem.equals("Beruwala")) {
        Needmethod2.Beruwala();
    }
 
    else if (selectedItem.equals("Dehiwala")) {
        Needmethod2.Dehiwala();
     }
    else if (selectedItem.equals("Wellawatte")) {
        Needmethod2.Wellawatte();
}
    else if (selectedItem.equals("Bambalapitiya")) {
        Needmethod2.Bambalapitiya();
    }    else if (selectedItem.equals("Kollupitiya")) {
    
         Needmethod2.Kollupitiya();
            }
    else if (selectedItem.equals("Galle face")) {
         Needmethod2.Galle_face();
   
}
    
}
    public UPDATE_NORMAL__USER_1() {
            initComponents();
            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            setFocusableWindowState(true); // Enable focusability for the window
            setFocusable(true); // Ensure frame is focusable
            setResizable(false); // Keep the window size fixed
            setLocationRelativeTo(null); // Center the window on the screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NU_NIC = new javax.swing.JTextField();
        NU_FNAME = new javax.swing.JTextField();
        NU_LNAME = new javax.swing.JTextField();
        NU_PNO = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        combox3 = new javax.swing.JComboBox<>();
        combox2 = new javax.swing.JComboBox<>();
        UPDATE = new javax.swing.JButton();
        RESET_BUTTON1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        combox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setFocusableWindowState(false);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setFocusCycleRoot(true);
        jPanel1.setFocusTraversalPolicyProvider(true);
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        NU_NIC.setFocusCycleRoot(true);
        NU_NIC.setFocusTraversalPolicyProvider(true);
        NU_NIC.setInheritsPopupMenu(true);
        NU_NIC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NU_NICMousePressed(evt);
            }
        });

        NU_PNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NU_PNOActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("ENTER FNAME                         :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("CHOOSE CURRENT LIVING AREA  :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("ENTER YOUR NIC                    :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("ENTER LNAME                         :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("CHOOSE DISTRICT                          :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("CHOOSE NEAREST BUS-HALT       :");

        combox3.setSelectedIndex(-1);
        combox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combox3ActionPerformed(evt);
            }
        });

        combox2.setSelectedIndex(-1);
        combox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combox2ActionPerformed(evt);
            }
        });

        UPDATE.setBackground(new java.awt.Color(0, 153, 255));
        UPDATE.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        UPDATE.setForeground(new java.awt.Color(255, 255, 255));
        UPDATE.setText("UPDATE");
        UPDATE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UPDATEMousePressed(evt);
            }
        });
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });

        RESET_BUTTON1.setBackground(new java.awt.Color(102, 102, 102));
        RESET_BUTTON1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        RESET_BUTTON1.setForeground(new java.awt.Color(255, 255, 255));
        RESET_BUTTON1.setText("BACK");
        RESET_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESET_BUTTON1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("ENTER PNO                              :");

        combox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kalutara", "Colombo" }));
        combox1.setSelectedIndex(-1);
        combox1.setSelectedItem(-1);
        combox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel1.setText("UPDATE USER DETAILS");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("* NIC IS REQUIRED");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(NU_LNAME)
                                    .addComponent(NU_PNO)
                                    .addComponent(NU_FNAME)
                                    .addComponent(NU_NIC)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addGap(0, 267, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(RESET_BUTTON1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(UPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NU_NIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NU_FNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(NU_LNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NU_PNO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(combox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UPDATE)
                    .addComponent(RESET_BUTTON1))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.getAccessibleContext().setAccessibleParent(jPanel1);

        getAccessibleContext().setAccessibleParent(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void combox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combox1ActionPerformed
        Districtchoose();
    }//GEN-LAST:event_combox1ActionPerformed

    private void RESET_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESET_BUTTON1ActionPerformed
       
       this.dispose(); //to close reset password form
    }//GEN-LAST:event_RESET_BUTTON1ActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed

    }//GEN-LAST:event_UPDATEActionPerformed

    private void UPDATEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPDATEMousePressed
// Variables for database connection


String jdbcUrl = "jdbc:mysql://localhost:3306/BUS"; // Database URL with database name (BUS)
String username = "root"; // MySQL username (default is 'root')
String password = ""; // MySQL password (leave empty if not set)

try {
    // Load MySQL JDBC Driver
    Class.forName("com.mysql.cj.jdbc.Driver");

    // Connect to the database
    try (Connection connection = DriverManager.getConnection(jdbcUrl, username, password)) {
        System.out.println("Connected to the database!");
         String enteredNUNIC                  = NU_NIC.getText();
        String enteredNUFName                = NU_FNAME.getText();
        String enteredNULName                = NU_LNAME.getText();
        String enteredNUPNO                  = NU_PNO.getText();
        
        String enteredNU_District            = (String) combox1.getSelectedItem();
        String enteredNU_living_area         = (String) combox2.getSelectedItem();
        String enteredNUNearest_bus_halt     = (String) combox3.getSelectedItem();
        // SQL query for updating user information
        String sql = "UPDATE NORMAL_USER " +
                     "SET FNAME = IF(? IS NOT NULL AND ? != '', ?, FNAME), " +
                     "    LNAME = IF(? IS NOT NULL AND ? != '', ?, LNAME), " +
                     "    PNO = IF(? IS NOT NULL AND ? != '', ?, PNO), " +
                     "    District = IF(? IS NOT NULL AND ? != '', ?, District), " +
                     "    LIVING_AREA = IF(? IS NOT NULL AND ? != '', ?, LIVING_AREA), " +
                     "    NEAREST_BUS_HALT= IF(? IS NOT NULL AND ? != '', ?, NEAREST_BUS_HALT) " +
                     "WHERE NIC = ?";

        //combox1.setSelectedItem(null);
        //combox2.setSelectedItem(null);
        //combox3.setSelectedItem(null);
        // Create a prepared statement
        try (PreparedStatement pstmt = connection.prepareStatement(sql)) {

            // Set parameters for the query
            pstmt.setString(1, enteredNUFName);
            pstmt.setString(2, enteredNUFName);
            pstmt.setString(3, enteredNUFName);

            pstmt.setString(4, enteredNULName);
            pstmt.setString(5, enteredNULName);
            pstmt.setString(6, enteredNULName);

            pstmt.setString(7, enteredNUPNO);
            pstmt.setString(8, enteredNUPNO);
            pstmt.setString(9, enteredNUPNO);

            pstmt.setString(10, enteredNU_District);
            pstmt.setString(11, enteredNU_District);
            pstmt.setString(12, enteredNU_District);

            pstmt.setString(13, enteredNU_living_area);
            pstmt.setString(14, enteredNU_living_area);
            pstmt.setString(15, enteredNU_living_area);

            pstmt.setString(16, enteredNUNearest_bus_halt);
            pstmt.setString(17, enteredNUNearest_bus_halt);
            pstmt.setString(18, enteredNUNearest_bus_halt);

            pstmt.setString(19, enteredNUNIC); // WHERE clause to identify the user by NIC

            // Execute the update query
            int rowsAffected = pstmt.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "User information updated successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "No matching user found to update.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "SQL Error: " + e.getMessage());
            e.printStackTrace();
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Database connection error: " + e.getMessage());
        e.printStackTrace();
    }
} catch (ClassNotFoundException e) {
    JOptionPane.showMessageDialog(null, "MySQL JDBC Driver not found.");
    e.printStackTrace();
}

//TO RESET ENTERED FIELDS AS NULL
 NU_NIC.setText("");
 NU_FNAME.setText("");
 NU_LNAME.setText("");
 NU_PNO.setText("");
 

    }//GEN-LAST:event_UPDATEMousePressed

    private void combox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combox2ActionPerformed
            Living_areachoose();
    }//GEN-LAST:event_combox2ActionPerformed

    private void NU_NICMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NU_NICMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NU_NICMousePressed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    private void combox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combox3ActionPerformed
              // TODO add your handling code here:
    }//GEN-LAST:event_combox3ActionPerformed

    private void NU_PNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NU_PNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NU_PNOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UPDATE_NORMAL__USER_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UPDATE_NORMAL__USER_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UPDATE_NORMAL__USER_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UPDATE_NORMAL__USER_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UPDATE_NORMAL__USER_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NU_FNAME;
    private javax.swing.JTextField NU_LNAME;
    private javax.swing.JTextField NU_NIC;
    private javax.swing.JTextField NU_PNO;
    private javax.swing.JButton RESET_BUTTON1;
    private javax.swing.JButton UPDATE;
    protected static javax.swing.JComboBox<String> combox1;
    protected static javax.swing.JComboBox<String> combox2;
    protected static javax.swing.JComboBox<String> combox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
